BACKPACKS_SEARCH = 'BACKPACKS_SEARCH'
BACKPACKS_IDLE = 'BACKPACKS_IDLE'
BACKPACKS_DISPLAYED = 'BACKPACKS_DISPLAYED'
BACKPACKS_NOTDISPLAYED = 'BACKPACKS_NOTDISPLAYED'

OPTION_CATEGORY = 'Category'
OPTION_QUALITY = 'Quality'
OPTION_RARITY = 'Rarity'
OPTION_LEVEL = 'Level'
OPTION_NAME = 'Name'

CHOICE_STANDARD = 'Standard'
