REGEX_LEVEL = /Level\s(\d+)/i
REGEX_TYPE_LIMITED = /(Limited)\s(Level|\w+)/i
REGEX_TYPE_STRANGE = /Strange\s.*\s-\s(.*):\s\d+/i
REGEX_RENAMED = /^(\'\'.*\'\')$/i
REGEX_GIFTED = /Gift\sfrom:\s(.*)/i
REGEX_CRAFTED = /Crafted\sby\s(.*)/i
REGEX_DESCRIPTION_STRANGE = /\((.*):\s(\d+)\)/i
REGEX_DESCRIPTION_STRANGE_KILLS = /^\s+Kills:\s(\d+)/i
REGEX_DESCRIPTION_PAINT = /Paint\sColor:\s(.*)/i
REGEX_DESCRIPTION_STYLE = /Style:\s(.*)/i
REGEX_DESCRIPTION_HALLOWEEN = /Halloween:\s(.*)\s\(spell only active during event\)/i
REGEX_DESCRIPTION_HOLIDAY = /Holiday\sRestriction:\s(.*)/i
REGEX_DESCRIPTION_KILLSTREAKER = /^Killstreaker:\s(.*)/i
REGEX_DESCRIPTION_SHEEN = /^Sheen:\s(.*)/i
REGEX_DESCRIPTION_UNUSUAL = /Unusual\sEffect:\s(.*)/i
REGEX_DESCRIPTION_MEDAL = /Medal\sno\.\s(\d+)/i
REGEX_DESCRIPTION_DEDICATION = /^Dedication:\s(.*)$/i
REGEX_DESCRIPTION_EVENT_DOTA2 = /((New\sBloom|Diretide|Frostivus|The\sInternational|Sithil\'s\sSummer\sStash|The\sCOmpendium\sFantasy\sChallenge)\s(\d{4}))/i
