console.log "< Steam item search in groups >"
console.log "\tCurrent Steam request per minute limit is < 30 >"
console.log "\t10 friends\t ~ 20 seconds"
console.log "\t100 friends\t ~ 3 minutes 20 seconds"
console.log "\t200 friends\t ~ 6 minutes 40 seconds"
console.log "</ Steam item search in groups >"
