console.log "< Steam item search between friends >"
console.log "\tCurrent Steam request per minute limit is < 2 >"
console.log "\t10 friends\t => 5 minutes"
console.log "\t100 friends\t => 50 minutes"
console.log "\t200 friends\t => 1 hour 40 minutes"
console.log "</ Steam item search between friends >"
